#!/bin/sh

mkdir ~/.vim_backup
mkdir ~/.vim_tmp

[ -d /data ] && DATA=/data || DATA=~/mydata
APPS=$DATA/Apps

[ -f $APPS/aliyunpan/aliyunpan ] && ln -s $APPS/aliyunpan/aliyunpan ~/.local/bin/
(
crontab -l | grep -v ^#
cat <<EOF
@hourly ALIYUNPAN_CONFIG_DIR=~/.config/aliyunpan $APPS/aliyunpan/aliyunpan token update
EOF
) | crontab -

cp -f ~/.xxinputrc ~/.xinputrc

# Initialize/update submodules
cd ~/ || exit
echo "Initializing submodules..."
yadm submodule update --init --recursive


#pip install --user https://github.com/shadowsocks/shadowsocks/archive/master.zip -U
#pip install --user trash-cli
