#!/bin/sh

mkdir ~/.vim_backup
mkdir ~/.vim_tmp

# Initialize/update submodules
cd "${HOME}"
echo "Initializing submodules..."
yadm submodule update --init --recursive


#pip install --user https://github.com/shadowsocks/shadowsocks/archive/master.zip -U
#pip install --user trash-cli
