#!/usr/bin/sh
# to be sourced
os_type="$(grep -oP "^ID=\"\K.*?(?=\")" /etc/os-release)";
if [ "${os_type}" = "opensuse-leap" ]; then
  XIMFILE=/etc/X11/xim
  test -r $HOME/.xim && XIMFILE=$HOME/.xim
  test -r $XIMFILE && source $XIMFILE
fi

#if [ -r "$HOME/.xinputrc" ]; then
#  . $HOME/.xinputrc
#fi
#ubuntu
if [ -r "/etc/X11/Xsession.d/70im-config_launch" ]; then
  . /etc/X11/Xsession.d/70im-config_launch
fi
