#!/usr/bin/sh
# to be sourced
# shellcheck source=/dev/null
os_type="$(grep -oP "^ID=\"\K.*?(?=\")" /etc/os-release)";
if [ "${os_type}" = "opensuse-leap" ]; then
  XIMFILE=/etc/X11/xim
  test -r ~/.xim && XIMFILE=~/.xim
  test -r $XIMFILE && . $XIMFILE
fi

#if [ -r "~/.xinputrc" ]; then
#  . ~/.xinputrc
#fi
#ubuntu
if [ -r "/etc/X11/Xsession.d/70im-config_launch" ]; then
  . /etc/X11/Xsession.d/70im-config_launch
fi
